[versions]
shadow = "9.3.1"
gradleideaext = "1.4.1"
annotations = "26.1.0"
gson = "2.13.2"
commonslang3 = "3.20.0"
spigot = "1.21.11-R0.2-SNAPSHOT"
boostedyaml = "1.3.7"
adventure = "4.26.1"
lamp = "3.3.6"
bstats = "3.2.1"


[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
gradleideaext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "gradleideaext" }

[libraries]
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
commonslang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonslang3" }
spigot = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }
boostedyaml = { module = "dev.dejvokep:boosted-yaml", version.ref = "boostedyaml" }
adventureapi = { module = "net.kyori:adventure-api", version.ref = "adventure" }
lampcommon = { module = "io.github.Revxrsal.Lamp:common", version.ref = "lamp" }
lampbukkit = { module = "io.github.Revxrsal.Lamp:bukkit", version.ref = "lamp" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }